# Generated by Django 3.2 on 2021-05-01 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210428_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sulg',
            new_name='slug',
        ),
    ]
